const fs = require('fs');
const path = require('path');

const species = [
  { name: 'Moose', scientific: 'Alces alces', slug: 'moose', category: 'Mammals', desc: 'The largest and heaviest extant species in the deer family, widely distributed across Norway\'s forests.', behavior: 'Solitary, browses on leaves and aquatic plants.', status: 'Least Concern', region: 'Eastern and Central Norway', season: 'May-October', image: 'https://images.unsplash.com/photo-1588698716380-60b77b949ab1?q=moose&w=1080' },
  { name: 'Reindeer', scientific: 'Rangifer tarandus', slug: 'reindeer', category: 'Mammals', desc: 'A species of deer with circumpolar distribution, native to Arctic, subarctic, tundra, boreal, and mountainous regions.', behavior: 'Migratory herds, active foraging.', status: 'Vulnerable', region: 'Hardangervidda, Northern Norway', season: 'All year', image: 'https://images.unsplash.com/photo-1543702404-03aeb69bfb01?q=reindeer&w=1080' },
  { name: 'Arctic fox', scientific: 'Vulpes lagopus', slug: 'arctic-fox', category: 'Mammals', desc: 'A small fox native to the Arctic regions of the Northern Hemisphere, known for its thick, warm fur.', behavior: 'Nomadic, hunts small rodents.', status: 'Endangered in Norway', region: 'Svalbard, Alpine tundra', season: 'Winter', image: 'https://images.unsplash.com/photo-1457459686225-c75dd9cfa426?q=arctic+fox&w=1080' },
  { name: 'Red fox', scientific: 'Vulpes vulpes', slug: 'red-fox', category: 'Mammals', desc: 'The largest of the true foxes and one of the most widely distributed members of the order Carnivora.', behavior: 'Solitary hunter, adaptable.', status: 'Least Concern', region: 'All over Norway', season: 'All year', image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?q=red+fox&w=1080' },
  { name: 'Eurasian lynx', scientific: 'Lynx lynx', slug: 'eurasian-lynx', category: 'Mammals', desc: 'A medium-sized wild cat occurring from Northern, Central and Eastern Europe to Central Asia.', behavior: 'Elusive, nocturnal hunter.', status: 'Near Threatened (Norway)', region: 'Boreal forests', season: 'Winter', image: 'https://images.unsplash.com/photo-1582215264375-926d83eeebfb?q=lynx&w=1080' },
  { name: 'Wolverine', scientific: 'Gulo gulo', slug: 'wolverine', category: 'Mammals', desc: 'The largest land-dwelling species of the family Mustelidae. It is a muscular carnivore.', behavior: 'Solitary, scavenges and hunts.', status: 'Endangered (Norway)', region: 'Mountainous regions, Finnmark', season: 'Winter', image: 'https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?q=wolverine+animal&w=1080' },
  { name: 'Brown bear', scientific: 'Ursus arctos', slug: 'brown-bear', category: 'Mammals', desc: 'A large bear species found across Eurasia and North America.', behavior: 'Solitary, hibernates in winter.', status: 'Endangered (Norway)', region: 'Pasvik, Hedmark', season: 'Summer', image: 'https://images.unsplash.com/photo-1534062060195-2c8c69ee386a?q=brown+bear&w=1080' },
  { name: 'Wolf', scientific: 'Canis lupus', slug: 'wolf', category: 'Mammals', desc: 'A large canine native to Eurasia and North America.', behavior: 'Pack hunter, highly territorial.', status: 'Critically Endangered (Norway)', region: 'Eastern Norway (Østerdalen)', season: 'All year', image: 'https://images.unsplash.com/photo-1560879311-370fd4561a0d?q=wolf&w=1080' },
  { name: 'Musk ox', scientific: 'Ovibos moschatus', slug: 'musk-ox', category: 'Mammals', desc: 'An Arctic hoofed mammal of the family Bovidae, noted for its thick coat and the strong odor emitted by males.', behavior: 'Forms defensive herds.', status: 'Least Concern', region: 'Dovrefjell National Park', season: 'Summer', image: 'https://images.unsplash.com/photo-1589136190760-b74751f043e7?q=musk+ox&w=1080' },
  { name: 'Roe deer', scientific: 'Capreolus capreolus', slug: 'roe-deer', category: 'Mammals', desc: 'A species of deer. The male of the species is sometimes referred to as a roebuck.', behavior: 'Crepuscular, solitary or small groups.', status: 'Least Concern', region: 'Southern and Central Norway', season: 'All year', image: 'https://images.unsplash.com/photo-1498661858852-c07a346536b5?q=roe+deer&w=1080' },
  { name: 'Red deer', scientific: 'Cervus elaphus', slug: 'red-deer', category: 'Mammals', desc: 'One of the largest deer species. The red deer inhabits most of Europe.', behavior: 'Herd-living, vocal during rut.', status: 'Least Concern', region: 'Western Norway', season: 'Autumn', image: 'https://images.unsplash.com/photo-1484557985045-edf25e08da73?q=red+deer&w=1080' },
  { name: 'Wild reindeer', scientific: 'Rangifer tarandus tarandus', slug: 'wild-reindeer', category: 'Mammals', desc: 'Norway has the last remaining populations of wild tundra reindeer in Europe.', behavior: 'Migratory.', status: 'Near Threatened', region: 'Hardangervidda, Rondane', season: 'Summer-Autumn', image: 'https://images.unsplash.com/photo-1512411939103-605bb16e8dd1?q=reindeer+wild&w=1080' },
  { name: 'Orca', scientific: 'Orcinus orca', slug: 'orca', category: 'Marine', desc: 'Also known as the killer whale, is a toothed whale belonging to the oceanic dolphin family, of which it is the largest member.', behavior: 'Highly social, hunts in pods.', status: 'Data Deficient', region: 'Northern Norway fjords', season: 'November-January', image: 'https://images.unsplash.com/photo-1582236113203-9bb6eb827a4f?q=orca&w=1080' },
  { name: 'Humpback whale', scientific: 'Megaptera novaeangliae', slug: 'humpback-whale', category: 'Marine', desc: 'A species of baleen whale. It is one of the larger rorqual species.', behavior: 'Acrobatic, complex songs.', status: 'Least Concern', region: 'Tromsø, Vesterålen', season: 'Winter', image: 'https://images.unsplash.com/photo-1502015243396-745aebf132e4?q=humpback+whale&w=1080' },
  { name: 'Sperm whale', scientific: 'Physeter macrocephalus', slug: 'sperm-whale', category: 'Marine', desc: 'The largest of the toothed whales and the largest toothed predator.', behavior: 'Deep diver, hunts squid.', status: 'Vulnerable', region: 'Vesterålen (Andenes)', season: 'Summer', image: 'https://images.unsplash.com/photo-1549420088-251f28b2ad46?q=sperm+whale&w=1080' },
  { name: 'Minke whale', scientific: 'Balaenoptera acutorostrata', slug: 'minke-whale', category: 'Marine', desc: 'A species of minke whale within the suborder of baleen whales.', behavior: 'Solitary, fast swimmer.', status: 'Least Concern', region: 'Coastal Norway', season: 'Summer', image: 'https://images.unsplash.com/photo-1521740924089-23db975de3bd?q=whale&w=1080' },
  { name: 'Harbour seal', scientific: 'Phoca vitulina', slug: 'harbour-seal', category: 'Marine', desc: 'Also known as the common seal, is a true seal found along temperate and Arctic marine coastlines of the Northern Hemisphere.', behavior: 'Hauls out on rocks, solitary hunter.', status: 'Least Concern', region: 'Coastal Norway', season: 'All year', image: 'https://images.unsplash.com/photo-1565575514660-8f3e53ba54ff?q=harbour+seal&w=1080' },
  { name: 'Grey seal', scientific: 'Halichoerus grypus', slug: 'grey-seal', category: 'Marine', desc: 'Found on both shores of the North Atlantic Ocean. It is a large seal of the family Phocidae.', behavior: 'Gregarious on land, dives deep.', status: 'Least Concern', region: 'Coastal islands', season: 'Autumn', image: 'https://images.unsplash.com/photo-1614210667496-e2448375086d?q=grey+seal&w=1080' },
  { name: 'Walrus', scientific: 'Odobenus rosmarus', slug: 'walrus', category: 'Marine', desc: 'A large flippered marine mammal with a discontinuous distribution about the North Pole.', behavior: 'Uses tusks to haul out, feeds on benthos.', status: 'Vulnerable', region: 'Svalbard', season: 'Summer', image: 'https://images.unsplash.com/photo-1577717646549-3543b35beaa7?q=walrus&w=1080' },
  { name: 'Harbour porpoise', scientific: 'Phocoena phocoena', slug: 'harbour-porpoise', category: 'Marine', desc: 'One of eight extant species of porpoise. It is one of the smallest marine mammals.', behavior: 'Shy, found in shallow coastal waters.', status: 'Least Concern', region: 'Fjords and coast', season: 'All year', image: 'https://images.unsplash.com/photo-1601328005886-f81dff90d96d?q=porpoise&w=1080' },
  { name: 'Atlantic puffin', scientific: 'Fratercula arctica', slug: 'atlantic-puffin', category: 'Birds', desc: 'A species of seabird in the auk family. It is the only puffin native to the Atlantic Ocean.', behavior: 'Nests in burrows, dives for fish.', status: 'Vulnerable', region: 'Røst, Bleik, Svalbard', season: 'Summer', image: 'https://images.unsplash.com/photo-1552554523-c90a880bf618?q=puffin&w=1080' },
  { name: 'White-tailed eagle', scientific: 'Haliaeetus albicilla', slug: 'white-tailed-eagle', category: 'Birds', desc: 'A very large species of sea eagle widely distributed across temperate Eurasia.', behavior: 'Soars along coastlines, hunts fish.', status: 'Least Concern', region: 'Nordland, coastal areas', season: 'All year', image: 'https://images.unsplash.com/photo-1530263628045-814197cc4bb4?q=eagle&w=1080' },
  { name: 'Golden eagle', scientific: 'Aquila chrysaetos', slug: 'golden-eagle', category: 'Birds', desc: 'One of the best-known birds of prey in the Northern Hemisphere.', behavior: 'Hunts small mammals in open areas.', status: 'Least Concern', region: 'Mountainous regions', season: 'All year', image: 'https://images.unsplash.com/photo-1496660144983-500b904944ec?q=golden+eagle&w=1080' },
  { name: 'Gyrfalcon', scientific: 'Falco rusticolus', slug: 'gyrfalcon', category: 'Birds', desc: 'The largest of the falcon species. It breeds on Arctic coasts and tundra.', behavior: 'Fast pursuit hunter.', status: 'Least Concern', region: 'Finnmark, Svalbard', season: 'Winter', image: 'https://images.unsplash.com/photo-1526435071190-bdfcb7547248?q=falcon&w=1080' },
  { name: 'Snowy owl', scientific: 'Bubo scandiacus', slug: 'snowy-owl', category: 'Birds', desc: 'A large, white owl of the true owl family. Native to the Arctic regions.', behavior: 'Diurnal hunter, feeds on lemmings.', status: 'Vulnerable', region: 'Finnmark, Hardangervidda', season: 'Winter', image: 'https://images.unsplash.com/photo-1518118014316-29a39f60e9a7?q=snowy+owl&w=1080' },
  { name: 'Arctic tern', scientific: 'Sterna paradisaea', slug: 'arctic-tern', category: 'Birds', desc: 'A seabird of the tern family Sternidae. Has the longest migration of any animal.', behavior: 'Aggressively defends nests.', status: 'Least Concern', region: 'Svalbard, Northern coast', season: 'Summer', image: 'https://images.unsplash.com/photo-1621532057393-0be9df863925?q=tern&w=1080' },
  { name: 'Razorbill', scientific: 'Alca torda', slug: 'razorbill', category: 'Birds', desc: 'A colonial seabird that comes to land only to breed. It is an agile swimmer.', behavior: 'Dives deeply for schooling fish.', status: 'Near Threatened', region: 'Coastal cliffs', season: 'Summer', image: 'https://images.unsplash.com/photo-1606558113264-b8d1b32d18cb?q=seabird&w=1080' },
  { name: 'Common guillemot', scientific: 'Uria aalge', slug: 'common-guillemot', category: 'Birds', desc: 'A large auk. It is also known as the common murre.', behavior: 'Nests in dense colonies on cliffs.', status: 'Least Concern', region: 'Coastal cliffs, Svalbard', season: 'Summer', image: 'https://images.unsplash.com/photo-1581022986873-1f1c713be246?q=guillemot&w=1080' },
  { name: 'Northern gannet', scientific: 'Morus bassanus', slug: 'northern-gannet', category: 'Birds', desc: 'A seabird and the largest species of the gannet family, Sulidae.', behavior: 'Plunge dives from heights to catch fish.', status: 'Least Concern', region: 'Runde, coastal islands', season: 'Summer', image: 'https://images.unsplash.com/photo-1549420088-251f28b2ad46?q=gannet&w=1080' },
  { name: 'Black-legged kittiwake', scientific: 'Rissa tridactyla', slug: 'kittiwake', category: 'Birds', desc: 'A species of seabird in the gull family Laridae.', behavior: 'Pelagic gull, nests on steep cliffs.', status: 'Vulnerable', region: 'Bird cliffs, Svalbard', season: 'Summer', image: 'https://images.unsplash.com/photo-1502470712753-4eb08e6f1f26?q=seagull&w=1080' },
  { name: 'Polar bear', scientific: 'Ursus maritimus', slug: 'polar-bear', category: 'Mammals', desc: 'A hypercarnivorous bear whose native range lies largely within the Arctic Circle.', behavior: 'Hunts seals on sea ice.', status: 'Vulnerable', region: 'Svalbard', season: 'Spring-Summer', image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?q=polar+bear&w=1080' },
  { name: 'Eurasian elk', scientific: 'Alces alces', slug: 'eurasian-elk', category: 'Mammals', desc: 'Also known as the moose in North America. The largest species in the deer family.', behavior: 'Solitary, woodland browser.', status: 'Least Concern', region: 'Boreal forests', season: 'Autumn', image: 'https://images.unsplash.com/photo-1517726589332-9c3db6cb2b6e?q=moose&w=1080' },
  { name: 'European otter', scientific: 'Lutra lutra', slug: 'european-otter', category: 'Mammals', desc: 'A semiaquatic mammal native to Eurasia.', behavior: 'Playful, hunts fish in rivers and coasts.', status: 'Near Threatened', region: 'Coastal and inland waterways', season: 'All year', image: 'https://images.unsplash.com/photo-1534005856417-64dfdf7a19bb?q=otter&w=1080' },
  { name: 'Mountain hare', scientific: 'Lepus timidus', slug: 'mountain-hare', category: 'Mammals', desc: 'A palearctic hare that is largely adapted to polar and mountainous habitats.', behavior: 'Changes coat color in winter.', status: 'Least Concern', region: 'Alpine tundra and forests', season: 'Winter', image: 'https://images.unsplash.com/photo-1518063001712-45e0a6d71b30?q=hare&w=1080' },
  { name: 'Svalbard reindeer', scientific: 'Rangifer tarandus platyrhynchus', slug: 'svalbard-reindeer', category: 'Mammals', desc: 'A small subspecies of reindeer endemic to the Svalbard archipelago.', behavior: 'Sedentary, accumulates heavy fat reserves.', status: 'Least Concern', region: 'Svalbard', season: 'Summer', image: 'https://images.unsplash.com/photo-1543702404-03aeb69bfb01?q=reindeer&w=1080' }
];

let sql = `-- Phase 12: National Content Expansion - Wildlife Data\n\n`;

for (const w of species) {
  const escapedName = w.name.replace(/'/g, "''");
  const escapedDesc = w.desc.replace(/'/g, "''");
  const escapedBehavior = w.behavior.replace(/'/g, "''");
  const escapedRegion = w.region.replace(/'/g, "''");
  
  // Create JSON array for facts (we'll store diet/category here)
  const facts = `ARRAY['Diet: Carnivore/Herbivore', 'Category: ${w.category}']`;

  sql += `INSERT INTO public.wildlife_species (id, common_name, scientific_name, slug, description, conservation_status, behavior, facts, source_type)\n`;
  sql += `VALUES (gen_random_uuid(), '${escapedName}', '${w.scientific}', '${w.slug}', '${escapedDesc}', '${w.status}', '${escapedBehavior}', ${facts}, 'editorial')\n`;
  sql += `ON CONFLICT (slug) DO UPDATE SET\n`;
  sql += `  common_name = EXCLUDED.common_name,\n`;
  sql += `  description = EXCLUDED.description,\n`;
  sql += `  conservation_status = EXCLUDED.conservation_status,\n`;
  sql += `  behavior = EXCLUDED.behavior;\n\n`;
  
  // Habitat
  sql += `INSERT INTO public.wildlife_habitats (id, species_id, region, best_months, description)\n`;
  sql += `SELECT gen_random_uuid(), id, '${escapedRegion}', ARRAY['${w.season}'], 'Preferred habitat region' FROM public.wildlife_species WHERE slug = '${w.slug}'\n`;
  sql += `ON CONFLICT DO NOTHING;\n\n`;

  // Media
  sql += `INSERT INTO public.content_media (id, entity_type, entity_id, media_type, media_url, alt_text)\n`;
  sql += `SELECT gen_random_uuid(), 'wildlife_species', id, 'GALLERY', '${w.image}', '${escapedName}' FROM public.wildlife_species WHERE slug = '${w.slug}'\n`;
  sql += `AND NOT EXISTS (SELECT 1 FROM public.content_media WHERE entity_type = 'wildlife_species' AND media_url = '${w.image}' AND entity_id = (SELECT id FROM public.wildlife_species WHERE slug = '${w.slug}'));\n\n`;
}

const migrationsDir = path.join(__dirname, '..', 'supabase', 'migrations');
if (!fs.existsSync(migrationsDir)) {
  fs.mkdirSync(migrationsDir, { recursive: true });
}

const targetFile = path.join(migrationsDir, '20260819000011_phase12_wildlife_data.sql');
fs.writeFileSync(targetFile, sql, 'utf8');

console.log('Successfully generated SQL script at:', targetFile);
